version: '3.3'

services:
  k8s_sql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: k8s
      MYSQL_PASSWORD: k8s
    ports:
      - "3306:3306"

  k8s-node:
    container_name: nodeapp
    image: "duttadeep55/k8s-node-sql:latest"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "80:8080"

volumes:
  db_data: {}